spring:
  datasource:
#    url: jdbc:mysql://182.92.88.94:3306/xcx-content-center
#    hikari:
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver #mysql connect >6
      url: jdbc:mysql://localhost:3306/xcx-content-center?serverTimezone=UTC
      hikari:
        username: root
        password: zjy123
        driver-class-name: com.mysql.cj.jdbc.Driver #mysql connect >6
#  application:
#    name: content-center
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
        #抽样率 默认0.1
      probability: 1.0
  cloud:
    nacos:
      discovery:
#        namespace: 21721849-4d73-4de5-8615-973a77605d69
        server-addr: localhost:8848
        cluster-name: BJ
        metadata:
          version: v1
          target-version: v1
    sentinel:
      transport:
        #指定sentinel控制台地址
        dashboard: localhost:8080
      filter:
        #关掉对springMVC端点的保护
        enabled: false
  main:
    allow-bean-definition-overriding: true #允许bean重名
server:
  port: 8090
#配置文件优先级高于java代码
#user-center:
#  ribbon:
##    NFLoadBalancerRulueClassName: com.netflix.loadbalancer.RandomRule
#    NFLoadBalancerRulueClassName: com.lengedyun.contentcenter.config.NacosWeightedRule
ribbon:
  eager-load:
    #多个逗号分隔
    clients: user-cneter
    enabled: true #开启饥饿加载，默认懒加载
logging:
  level:
    com.lengedyun.contentcenter.feign.UserCenterFeignClient: debug
    com.lengedyun.contentcenter.dao: debug
feign:
  client:
    config:
      default:
        loggerLevel: full  #生产建议使用BASIC
        requestInterceptors:
          - com.lengedyun.contentcenter.feign.interceptor.TokenRelayRequestInterceptor
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

#actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    #必须指定group
    group: test-group

#your:
#  config: zjy

